---
# - name: debug
#   debug: var=item

# - name: item debug
#   debug:
#     msg: '{{ item | to_json}}'
#     #msg: "item: {{ item | to_nice_json }}"

# - name: item.cmd
#   debug:
#     msg: 'item.cmd = {{ item.cmd }}'
# - name: item.regex
#   debug:
#     msg: 'item.regex = {{ item.regex }}'

- name: Exec linux command {{ item.cmd }}
  shell: "{{ item.cmd }} 2>/dev/null"
  register: cmd_output
  ignore_errors: True
  #check_mode: yes

# - debug:
#     msg: 'cmd_output = {{ cmd_output.stdout }}'

- set_fact:
    regexp_pattern: "{{ item.regex }}"

# - debug:
#     msg: "regexp_pattern = {{ regexp_pattern }}"

- set_fact:
    # regexp: '{{ item.regex }}'
    regexOutput: "{{ cmd_output.stdout | regex_search(item.regex) }}"

- debug:
    msg : "regexOutput = {{ regexOutput }}"

- set_fact:
    lOutput : {
      "cmd" : "{{ item.cmd }}",
      "regex" : "{{ item.regex }}",
      "cmd_output" : "{{ cmd_output.stdout }}",
      "regex_output" : "{{ regexOutput }}",
    }

- set_fact:
    ezOutput : "{{ezOutput}} + [{{lOutput}}]"